from .basicmessage import MESSAGE_TYPES as BASIC_MESSAGE_MESSAGE_TYPES
from .connections_new import MESSAGE_TYPES as CONNECTION_NEW_MESSAGE_TYPES
from .connections import MESSAGE_TYPES as CONNECTIONS_MESSAGE_TYPES

MESSAGE_TYPES = {}
MESSAGE_TYPES.update(BASIC_MESSAGE_MESSAGE_TYPES)
MESSAGE_TYPES.update(CONNECTION_NEW_MESSAGE_TYPES)
MESSAGE_TYPES.update(CONNECTIONS_MESSAGE_TYPES)
