from .basicmessage import MESSAGE_TYPES as BASIC_MESSAGE_MESSAGE_TYPES
from .connections_new import MESSAGE_TYPES as CONNECTION_NEW_MESSAGE_TYPES
from .connections import MESSAGE_TYPES as CONNECTIONS_MESSAGE_TYPES
from .credential_definitions import (
    MESSAGE_TYPES as CREDENTIAL_DEFINITIONS_MESSAGE_TYPES,
)
from .dids import MESSAGE_TYPES as DIDS_MESSAGE_TYPES

MESSAGE_TYPES = {}
MESSAGE_TYPES.update(BASIC_MESSAGE_MESSAGE_TYPES)
MESSAGE_TYPES.update(CONNECTION_NEW_MESSAGE_TYPES)
MESSAGE_TYPES.update(CONNECTIONS_MESSAGE_TYPES)
MESSAGE_TYPES.update(CREDENTIAL_DEFINITIONS_MESSAGE_TYPES)
MESSAGE_TYPES.update(DIDS_MESSAGE_TYPES)
