version: "3"
services:
  ngrok:
    image: wernight/ngrok
    command: ngrok http agent:3000 --log stdout
  agent:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      NGROK_NAME: ngrok
      AGENT_NAME: MyAgent
      PORT: 3000
      ADMIN_PORT: 3001
