version: "3"
services:
  agent-alice:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    network_mode: host
    environment:
      AGENT_NAME: Alice
      PORT: 3000
      ADMIN_PORT: 3001
      NO_NGROK: 1

  agent-bob:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    network_mode: host
    environment:
      AGENT_NAME: Bob
      PORT: 3002
      ADMIN_PORT: 3003
      NO_NGROK: 1
