version: "3"
services:
  agent-alice:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      AGENT_NAME: Alice
      PORT: 3000
      ADMIN_PORT: 3001
      NO_NGROK: 1
      ENDPOINT: http://host.docker.internal:3000/
    ports:
      - "3000:3000"
      - "3001:3001"

  agent-bob:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      AGENT_NAME: Bob
      PORT: 3002
      ADMIN_PORT: 3003
      NO_NGROK: 1
      ENDPOINT: http://host.docker.internal:3002/
    ports:
      - "3002:3002"
      - "3003:3003"
