#!/usr/bin/env bash

# Allow use of other engines (i.e. podman) through env var
CONTAINER_RUNTIME=${CONTAINER_RUNTIME:-docker}

cd "$(dirname "$0")" || exit 1

# Build image
$CONTAINER_RUNTIME build -t acapy-toolbox -f ../docker/Dockerfile ..

# Run the image with the default configuration (no args required)
$CONTAINER_RUNTIME run -it --rm -p 3000:3000 -p 3001:3001 acapy-toolbox
