label: Bob
invite-label: Bob (Admin)
wallet-name: bob
endpoint:
  - http://localhost:3002
  - ws://localhost:3002
inbound-transport:
  - [acapy_plugin_toolbox.http_ws, 0.0.0.0, 3002]
admin: [0.0.0.0, 3003]
